<!--
Copyright (C) 2026 Prosperismo Project
SPDX-License-Identifier: GPL-2.0-or-later
-->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>Prosperismo</AssemblyName>
    <RootNamespace>Prosperismo.Shell.App</RootNamespace>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <RuntimeIdentifiers>osx-arm64;osx-x64;win-x64;linux-x64</RuntimeIdentifiers>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Prosperismo.Shell\Prosperismo.Shell.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\..\assets\big-picture\**\*"
          Link="assets\big-picture\%(RecursiveDir)%(Filename)%(Extension)"
          CopyToOutputDirectory="PreserveNewest"
          CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
